// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Warehouse.Persistence;

#nullable disable

namespace Warehouse.Persistence.Migrations
{
    [DbContext(typeof(WarehouseContext))]
    [Migration("20250317141229_RenameWarehouseIdToBookId")]
    partial class RenameWarehouseIdToBookId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Warehouse.Domain.Entities.BaseOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("OperationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("operation_date");

                    b.Property<string>("operation_type")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)")
                        .HasColumnName("operation_type");

                    b.HasKey("Id")
                        .HasName("pk_operations");

                    b.ToTable("operations", (string)null);

                    b.HasDiscriminator<string>("operation_type").HasValue("BaseOperation");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Warehouse.Domain.Entities.OperationItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<int>("OperationId")
                        .HasColumnType("integer")
                        .HasColumnName("operation_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.HasKey("Id")
                        .HasName("pk_operation_items");

                    b.HasIndex("OperationId")
                        .HasDatabaseName("ix_operation_items_operation_id");

                    b.ToTable("operation_items", (string)null);
                });

            modelBuilder.Entity("Warehouse.Domain.Entities.WarehouseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_warehouse_items");

                    b.ToTable("warehouse_items", (string)null);
                });

            modelBuilder.Entity("Warehouse.Domain.Entities.ReceiptOperation", b =>
                {
                    b.HasBaseType("Warehouse.Domain.Entities.BaseOperation");

                    b.HasDiscriminator().HasValue("ReceiptOperation");
                });

            modelBuilder.Entity("Warehouse.Domain.Entities.WriteOffOperation", b =>
                {
                    b.HasBaseType("Warehouse.Domain.Entities.BaseOperation");

                    b.HasDiscriminator().HasValue("WriteOffOperation");
                });

            modelBuilder.Entity("Warehouse.Domain.Entities.OperationItem", b =>
                {
                    b.HasOne("Warehouse.Domain.Entities.BaseOperation", "Operation")
                        .WithMany("OperationItems")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_operation_items_base_operations_operation_id");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("Warehouse.Domain.Entities.BaseOperation", b =>
                {
                    b.Navigation("OperationItems");
                });
#pragma warning restore 612, 618
        }
    }
}
